#!/usr/bin/env python3
"""Convert RoboDojo wrench/00001 USDZ without redesigning its visual mesh.

Run with usd-core, numpy, trimesh and coacd installed. Source and output paths
are explicit arguments; only format conversion and rigid centering are applied.
"""
import argparse
import hashlib
import json
from pathlib import Path

import coacd
import numpy as np
import trimesh
from pxr import Usd, UsdGeom


def extract(stage, path):
    mesh = UsdGeom.Mesh(stage.GetPrimAtPath(path))
    transform = UsdGeom.XformCache().GetLocalToWorldTransform(mesh.GetPrim())
    points = np.array([transform.Transform(p) for p in mesh.GetPointsAttr().Get()])
    points *= UsdGeom.GetStageMetersPerUnit(stage)
    counts = list(mesh.GetFaceVertexCountsAttr().Get())
    assert set(counts) == {3}, "Expected the source triangulated mesh"
    faces = np.array(mesh.GetFaceVertexIndicesAttr().Get()).reshape((-1, 3))
    return points, faces


def obj(path, points, faces):
    lines = ['# Converted from RoboDojo wrench/00001; source geometry preserved.']
    lines += ['v ' + ' '.join(f'{v:.9f}' for v in p) for p in points]
    lines += ['f ' + ' '.join(str(int(i) + 1) for i in f) for f in faces]
    path.write_text('\n'.join(lines) + '\n')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    parser.add_argument('module', type=Path)
    args = parser.parse_args()
    stage = Usd.Stage.Open(str(args.source))
    assert UsdGeom.GetStageUpAxis(stage) == 'Z'
    points, faces = extract(stage, '/World/visual')
    center = (points.min(0) + points.max(0)) / 2
    points -= center
    # A half turn puts the wider open end toward the frame, away from Arm 1.
    points[:, :2] *= -1
    args.output.mkdir(parents=True, exist_ok=True)
    obj(args.output / 'robodojo-wrench.obj', points, faces)

    collision_points, collision_faces = extract(stage, '/World/collision')
    collision_points -= center
    collision_points[:, :2] *= -1
    mesh = trimesh.Trimesh(collision_points, collision_faces, process=True)
    coacd.set_log_level('error')
    # Voxel preprocessing expands this thin stamped tool by almost 1 mm.
    # Decompose the original surface directly to retain its contact envelope.
    parts = coacd.run_coacd(coacd.Mesh(mesh.vertices, mesh.faces), threshold=.015, preprocess_mode='off',
                           mcts_iterations=80, mcts_max_depth=4, seed=0)
    assets = ['<mesh name="robodojo_wrench_visual" file="tools/robodojo-wrench.obj"/>']
    geoms = []
    for i, (vertices, triangles) in enumerate(parts):
        name = f'robodojo_wrench_collision_{i}'
        filename = f'robodojo-wrench-collision-{i}.obj'
        obj(args.output / filename, vertices, triangles)
        assets.append(f'<mesh name="{name}" file="tools/{filename}"/>')
        geoms.append(f'<geom name="{name}" type="mesh" mesh="{name}" rgba="0 0 0 0" mass="{.15 / len(parts):.9f}" friction="1 .005 .001" condim="6" solref=".004 1" solimp=".99 .999 .0001"/>')
    # Source material is uniform gray; preserve it without the tool repaint shader.
    body = '<body name="open_end_wrench" pos="0 -.48 .121079">\n<freejoint/>\n'
    body += '<geom name="robodojo_wrench_visual" type="mesh" mesh="robodojo_wrench_visual" rgba=".49615762 .49615762 .49615762 1" contype="0" conaffinity="0" mass="0"/>\n'
    body += '\n'.join(geoms) + '\n</body>'
    args.module.write_text('// Generated by scripts/convert-robodojo-wrench.py from RoboDojo wrench/00001.\n'
                           + 'export const WRENCH_ASSET_XML = ' + json.dumps('\n'.join(assets)) + ';\n'
                           + 'export const WRENCH_BODY_XML = ' + json.dumps(body) + ';\n')
    (args.output / 'robodojo-wrench.json').write_text(json.dumps({
        'source': 'RoboDojo/Assets/Object/RoboDojo/Rigid/wrench/00001/object.usdz',
        'sourceSha256': hashlib.sha256(args.source.read_bytes()).hexdigest(),
        'vertices': len(points), 'triangles': len(faces),
        'bounds': [points.min(0).tolist(), points.max(0).tolist()],
        'collisionParts': len(parts), 'massKg': .15,
        'assetXml': '\n'.join(assets), 'bodyXml': body,
    }, indent=2) + '\n')
    print(json.dumps({'vertices': len(points), 'triangles': len(faces),
                      'extents': np.ptp(points, axis=0).tolist(), 'collisionParts': len(parts)}))


if __name__ == '__main__':
    main()
